; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.22816.0 

	TITLE	C:\Users\BinMatsui\Downloads\zlib128\zlib-1.2.8\inffast.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

END
